version: "3.8"

volumes:
  db-postgresql-volume:
    external: true

networks:
  instavote:
    driver: bridge

services:
  vote:
    image: rsshekhar/vote:master
    build: ./vote
    ports:
      - 5000:80
    depends_on:
      - redis
    networks:
      - instavote


  redis:
    image: redis:alpine
    networks:
      - instavote


  db:
    restart: always
    image: postgres:9.6
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db-postgresql-volume:/var/lib/postgresql:Z
    networks:
      - instavote

  result:
    image: rsshekhar/result:master
    build: ./result
    ports:
      - 5001:4000
    depends_on:
      - db
    networks:
      - instavote


  worker:
    image: rsshekhar/worker:master
    build: ./worker
    depends_on:
      - redis
      - db
    networks:
      - instavote
