pipeline{
  agent any

  tools{
    maven 'maven 3.8.2'
  }

  stages{
    stage("build"){
      steps{
        echo 'Compiling Worker App'
        dir('worker'){
          sh 'mvn compile'
        }
      }
    }

    stage("test"){
      steps{
        echo 'Running Unit Tests on worker app'
        dir('worker'){
            sh 'mvn clean test'
        }
      }
    }

    stage("package"){
      steps{
        echo 'Packaging worker app'
        dir('worker'){
            sh 'mvn package -DskipTests'
        }
      }
    }
  }

  post{
    always{
      archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
      echo 'Multibranch pipeline for worker is completed..'
    }
  }

}
